// 随看本 static projection — generated by scripts/build_memory_notes.py; do not edit by hand.
window.__NOTES_DATA__ = {"schema":2,"generated_at":"2026-10-08T15:26:47.769601+00:00","stats":{"total":0,"by_area":{"math2_gaoshu":0,"math2_xiandai":0,"ds":0,"co":0,"os":0,"cn":0}},"notes":[]};
